# Generated by Django 5.0.1 on 2024-02-10 03:06

import chatapp.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', chatapp.manager.CustomUserManager()),
            ],
        ),
    ]
