# Generated by Django 5.0.1 on 2024-02-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
