# Generated by Django 5.0.1 on 2024-02-10 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_group_name_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
