# Generated by Django 5.0.1 on 2024-02-26 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_profile_last_seen_profile_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sendtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='createtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
